### ISSUE TITLE
HTTP/S Certificate verification fails

### ISSUE THREAD

**Issue by montesound** [TechnikEmpire/CitadelCore#41]
This is with CitadelCore 2.2.3

2018-06-01 09:58:12.8820 INFO Request https://billing.vispnet.ca/projects/piwi/index.php?NEWSESSION/ whitelisted by rule @@||billing.vispnet.ca in category /default/whitelist/rules.
2018-06-01 09:58:12.8820 INFO Connection from local:59476 -> remote:443 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616
2018-06-01 09:58:15.8880 INFO Connection from local:59476 -> remote:443 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616
2018-06-01 09:58:21.8890 INFO Connection from local:59476 -> remote:443 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616
2018-06-01 09:58:23.5133 INFO Connection from local:59477 -> remote:80 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616
2018-06-01 09:58:33.8971 ERROR An error occurred while sending the request.   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CitadelCore.Net.Handlers.FilterHttpResponseHandler.<Handle>d__6.MoveNext()Unable to connect to the remote server   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 66.244.214.7:443   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
	 From FilterHttpResponseHandler.cs::Handle() #263
2018-06-01 09:58:34.1942 INFO Request https://billing.vispnet.ca/favicon.ico whitelisted by rule @@||billing.vispnet.ca in category /default/whitelist/rules.
2018-06-01 09:58:34.1942 INFO Connection from local:59478 -> remote:443 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616
2018-06-01 09:58:37.1967 INFO Connection from local:59478 -> remote:443 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616
2018-06-01 09:58:43.1977 INFO Connection from local:59478 -> remote:443 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616
2018-06-01 09:58:46.2524 INFO RESPONSE	 WindowsDiverter.cs::HandleNewTcpConnection() #678
2018-06-01 09:58:46.2524 INFO Connection from local:59357 -> remote:59479 outbound is our process.	 WindowsDiverter.cs::HandleNewTcpConnection() #616

**Comment by TechnikEmpire** [comment]
@montesound Thanks for the report. I'll look into this ASAP.

**Comment by TechnikEmpire** [comment]
Possible issue with Microsoft's security stack not using the AIA extension to resolve intermediaries and also not adding newly discovered trusts to the store.

If that's the case, we need to override the server verification handler in `ServicePointManager`  and doing this ourselves. The only problem is that we need to make sure that we do this properly because screwing this up means destroying encryption which means we forever lose trust.

Related articles:

https://dotnetcodr.com/2015/06/11/https-and-x509-certificates-in-net-part-5-validating-certificates-in-code/

But this falls short because we need to manage our own trust chain.

**Comment by TechnikEmpire** [comment]
Should really hash this out once and for all because this same bug (if I'm right) stands in the way of a proper C++ engine as well.
