### ISSUE TITLE
when I tested CitadelCore.Windows and got the traffic error as described

### ISSUE THREAD

**Issue by tuntin9x** [TechnikEmpire/CitadelCore#77]
ERRO: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.   at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
   at CitadelCore.Extensions.HttpRequestMessageExtensions.PopulateHeaders(HttpRequestMessage message, NameValueCollection headers, HashSet`1 exemptedHeaders) in C:\Github\CitadelCore\CitadelCore\Extensions\HttpRequestMessageExtensions.cs:line 54
   at CitadelCore.Net.Handlers.FilterHttpResponseHandler.Handle(HttpContext context) in C:\Github\CitadelCore\CitadelCore\Net\Handlers\FilterHttpResponseHandler.cs:line 217
         From FilterHttpResponseHandler.cs::Handle() #705

**Comment by TechnikEmpire** [comment]
This is expected behavior by design. Disable the exception in your debugger.
